events {
    worker_connections 1024;
}

http {
    server {
        server_name dockertar.zapto.org;

        location / {
            proxy_pass http://localhost:3000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }  
        location /dockerhub/ {
            add_header Access-Control-Allow-Origin *;
            proxy_pass https://hub.docker.com/;
        }

        location /install {
            proxy_pass http://localhost:8080/install/image-tar;
        }
    
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/dockertar.zapto.org/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/dockertar.zapto.org/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

    server {
    if ($host = dockertar.zapto.org) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


        listen 80;
        server_name dockertar.zapto.org;
    return 404; # managed by Certbot


}}