name: Remote SSH Command
on: [push]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VM_HOST }}
          key: ${{ secrets.SSH_KEY }}
          script: |

            set -e

            echo "Writing backend config ..."
            echo "${{ secrets.BACKEND_CONFIG }}" | tr -d '\r' > /home/solid/docker-tar/back-end/config.yaml

            echo "Deploying..."
            sudo /home/solid/deploy.sh